[package]
name = "ncht-manager"
version = "0.1.0"
authors = ["haryu703"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
itertools = "0.9.0"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.4.0"
dotenv = "0.15.0"
