name: Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: "docker.pkg.github.com/${{ github.repository }}/ncht-manager:latest"

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "${IMAGE_TAG}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${IMAGE_TAG}"
    - run: docker push "${IMAGE_TAG}"
