name: Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ncht-manager:latest
    - run: docker login -u ${{ secrets.OWNER }} -p ${{ secrets.GITHUB_TOKEN }}
    - run: docker push docker.pkg.github.com/${{ github.repository }}/ncht-manager:latest
